Plugins/Nop.Plugin.Baramjk.Core.MyFatoorah/Models/Suppliers/ProductSupplierViewModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Baramjk.Core.MyFatoorah.Models.Suppliers
{
    public record ProductSupplierViewModel: BaseNopEntityModel
    {
        public int ProductId { get; set; }
        
        [NopResourceDisplayName("Nop.Plugin.Baramjk.Core.MyFatoorah.Admin.Suppliers.Product.Supplier")]
        public int SupplierId { get; set; }

        public IList<SelectListItem> AvailableSuppliers { get; set; } = new List<SelectListItem>();

    }
}

Plugins/Nop.Plugin.Baramjk.Core.MyFatoorah/Controllers/SupplierAdminController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Plugin.Baramjk.Core.MyFatoorah.Domains;
using Nop.Plugin.Baramjk.Core.MyFatoorah.Factories;
using Nop.Plugin.Baramjk.Core.MyFatoorah.Models.Suppliers;
using Nop.Plugin.Baramjk.Core.MyFatoorah.Plugins;
using Nop.Plugin.Baramjk.Core.MyFatoorah.Services;
using Nop.Plugin.Baramjk.Framework.Mvc.Controller;
using Nop.Plugin.Baramjk.Framework.Mvc.Filters;
using Nop.Services.Catalog;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Web.Framework;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Baramjk.Core.MyFatoorah.Controllers
{
    [Permission(PermissionProvider.MyFatoorahManagement)]
    [Area(AreaNames.Admin)]
    [Route("Admin/MyFatoorah/Supplier/[action]")]
    public class SupplierAdminController : BaseBaramjkPluginController
    {
        private readonly SupplierAdminFactory _supplierFactory;
        private readonly SupplierService _supplierService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly INotificationService _notificationService;
        private readonly IProductService _productService;
        private readonly MyFatoorahSettings _myFatoorahSettings;

        public SupplierAdminController(
            SupplierAdminFactory supplierFactory,
            SupplierService supplierService,
            ILocalizedEntityService localizedEntityService,
            INotificationService notificationService, 
            IProductService productService,
            MyFatoorahSettings myFatoorahSettings)
        {
            _supplierFactory = supplierFactory;
            _supplierService = supplierService;
            _localizedEntityService = localizedEntityService;
            _notificationService = notificationService;
            _productService = productService;
            _myFatoorahSettings = myFatoorahSettings;
        }

        protected override string GetViewPath(string viewName) =>
            $"~/Plugins/{SystemName}/Views/Suppliers/{viewName}";

        public async Task SubmitLocalizationsAsync(Supplier supplier, IList<SupplierLocalizationModel> localizations)
        {
            foreach (var model in localizations)
            {
                await _localizedEntityService
                    .SaveLocalizedValueAsync(
                        supplier, 
                        b => b.Name, 
                        model.Name, 
                        model.LanguageId);
            }
        }

        [HttpGet]
        public IActionResult List()
        {
            var searchModel = new SupplierSearchModel();
            searchModel.SetGridPageSize();

            return View("List.cshtml", searchModel);
        }

        [HttpPost]
        public async Task<IActionResult> ListAsync(SupplierSearchModel searchModel)
        {
            var listModel = await _supplierFactory.PrepareListModelAsync(searchModel);
            return Json(listModel);
        }
        
        [HttpGet("{id:int}")]
        public async Task<IActionResult> EditAsync(int id)
        {
            var supplier = await _supplierService.GetByIdAsync(id);
            if (supplier == null)
            {
                _notificationService.ErrorNotification("Supplier not found.");
                return RedirectToAction("List");
            }
            var viewModel = await _supplierFactory.PrepareViewModelAsync(supplier);
            return View("Edit.cshtml", viewModel);
        }
        
        [HttpPost("{id:int}"), ParameterBasedOnFormName("save-continue", "continueEditing")]
        public async Task<IActionResult> EditAsync(int id, [FromForm] SupplierViewModel viewModel, bool continueEditing)
        {
            if (id != viewModel.Id)
                return RedirectToAction("List");

            if (viewModel.SupplierCode <= 0)
            {
                _notificationService.ErrorNotification("invalid supplier code.");
                return RedirectToAction("Edit", new { id });
            }
            
            var supplier = await _supplierService.GetByIdAsync(viewModel.Id);
            if (supplier == null)
            {
                _notificationService.ErrorNotification("Supplier not found.");
                return RedirectToAction("List");
            }

            supplier.Name = viewModel.Name;
            
            await _supplierService.UpdateAsync(supplier);
            await SubmitLocalizationsAsync(supplier, viewModel.Locales);
            
            return continueEditing
                ? RedirectToAction("Edit", new { id = viewModel.Id })
                : RedirectToAction("List");
        }
        
        [HttpPost]
        public async Task<IActionResult> AssignProductAsync(ProductSupplierViewModel viewModel)
        {
            if(viewModel.SupplierId <= 0)
                return BadRequest("Invalid supplier id.");
            
            if(viewModel.ProductId <= 0)
                return BadRequest("Invalid product id.");

            var supplier =  await _supplierService.GetByIdAsync(viewModel.SupplierId);
            if(supplier == null)
                return BadRequest("Supplier not found.");

            var product = await _productService.GetProductByIdAsync(viewModel.ProductId);
            if(product == null)
                return BadRequest("Product not found.");
            
            await _supplierService.AssignProductAsync(viewModel.ProductId, viewModel.SupplierId);
            return Ok();
        }

        [HttpGet]
        public async Task<IActionResult> SyncAsync()
        {
            if (_myFatoorahSettings.MyFatoorahUseSandbox)
            {
                _notificationService.ErrorNotification("Syncing suppliers is not allowed in sandbox mode.");
                return RedirectToAction("List");
            }
            
            await _supplierService.SyncSuppliersAsync();
            _notificationService.SuccessNotification("Suppliers synced successfully.");
            return RedirectToAction("List");
        }
    }
}

Plugins/Nop.Plugin.Baramjk.Core.MyFatoorah/Views/Widgets/ProductSupplier.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Nop.Core
@using Nop.Services.Common
@using Nop.Web.Framework.TagHelpers.Admin
@model Nop.Plugin.Baramjk.Core.MyFatoorah.Models.Suppliers.ProductSupplierViewModel

@inject IGenericAttributeService GenericAttributeService
@inject IWorkContext WorkContext

@{
    const string hideProductSupplierName = "Product.HideProductSupplier";
    var hideProductSupplierBlock = await GenericAttributeService.GetAttributeAsync<bool>(await WorkContext.GetCurrentCustomerAsync(), hideProductSupplierName);
}

<nop-card asp-name="product-supplier"
          asp-icon="fas fa-info"
          asp-hide-block-attribute-name="@hideProductSupplierName"
          asp-hide="@hideProductSupplierBlock"
          asp-title=@T("Nop.Plugin.Baramjk.Core.MyFatoorah.Admin.Suppliers.Product.AssignSupplier")
          asp-advanced="false">

    <div class="card-body">
        <div class="form-group row">
            <div class="col-md-3">
                <nop-label asp-for="SupplierId"/>
            </div>
            <div class="col-md-9">
                <nop-select id="supplierList" asp-for="SupplierId" asp-items="@Model.AvailableSuppliers"/>
                <span asp-validation-for="SupplierId"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="text-center col-12">
                <button type="button" id="setProductSupplier" class="btn btn-primary">
                    @T("Nop.Plugin.Baramjk.Core.MyFatoorah.Admin.Suppliers.Product.Assign")
                </button>
            </div>
        </div>
        
    </div>

    <script>

        $('#setProductSupplier').click(function() {
            const data = {
                "SupplierId": $('#supplierList').val(),
                "ProductId": '@(Model.ProductId)',
            };
            addAntiForgeryToken(data);
            $.ajax({
                cache: false,
                type: "POST",
                url: "@Url.Action("AssignProduct", "SupplierAdmin")",
                data: data,
                success: function () {
                    alert('@T("Nop.Plugin.Baramjk.Core.MyFatoorah.Admin.Suppliers.Product.AssignSuccessful")');
                },
                error: function (data){
                    alert("assign failed: " + data);
                },
                complete: function (jqXHR, textStatus) {
                }
            });
        });

    </script>
    
</nop-card>