Plugins/Nop.Plugin.Baramjk.PhotoPlatform/Models/Api/ContactUs/ContactInfos/SubmitContactInfoApiParams.cs
namespace Nop.Plugin.Baramjk.PhotoPlatform.Models.Api.ContactUs.ContactInfos
{
    public class SubmitContactInfoApiParams
    {
        public string FirstName { get; set; }
        
        public string LastName { get; set; }
        
        public int TicketId { get; set; }
        
        public int CountryId { get; set; }
        
        public string PhoneNumber { get; set; }
        
        public string Email { get; set; }
        
        public int SubjectId { get; set; }
        
        public string FileGuid { get; set; }
        
        public string Message { get; set; }
        
    }
}

Plugins/Nop.Plugin.Baramjk.PhotoPlatform/Models/Api/ContactUs/ContactInfos/SubmitContactInfoApiResults.cs
namespace Nop.Plugin.Baramjk.PhotoPlatform.Models.Api.ContactUs.ContactInfos
{
    public class SubmitContactInfoApiResults
    {
        public bool DoseNeedToPay { get; set; }
        
        public string PaymentUrl { get; set; }
        
    }
}

Plugins/Nop.Plugin.Baramjk.PhotoPlatform/Models/Api/ContactUs/OwnerInfo/OwnerInfoApiResponse.cs
using Nop.Plugin.Baramjk.Framework.Dto.Abstractions;

namespace Nop.Plugin.Baramjk.PhotoPlatform.Models.Api.ContactUs.OwnerInfo
{
    public class OwnerInfoApiResponse: CamelCaseBaseDto
    {
        public string Email { get; set; }
        
        public string PhoneNumber { get; set; }
    }
}

Plugins/Nop.Plugin.Baramjk.PhotoPlatform/Models/Api/ContactUs/Payments/PaymentDto.cs
using Nop.Plugin.Baramjk.Framework.Dto.Abstractions;

namespace Nop.Plugin.Baramjk.PhotoPlatform.Models.Api.ContactUs.Payments
{
    public class PaymentDto: CamelCaseModelDto
    {
        public string PaymentMethodSystemName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Fee { get; set; }
        public bool Selected { get; set; }
        public string LogoUrl { get; set; }
    }
}

Plugins/Nop.Plugin.Baramjk.PhotoPlatform/Models/Api/ContactUs/Subject/SubjectDto.cs
using Nop.Plugin.Baramjk.Framework.Dto.Abstractions;

namespace Nop.Plugin.Baramjk.PhotoPlatform.Models.Api.ContactUs.Subject
{
    public class SubjectDto: CamelCaseModelWithIdDto
    {
        public string Name { get; set; }

        public bool IsPayable => Price > 0;
        
        public decimal Price { get; set; }
        
        public string PriceString { get; set; }
    }
}

Plugins/Nop.Plugin.Baramjk.PhotoPlatform/Areas/Admin/Controllers/ContactUsSubjectController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Plugin.Baramjk.Framework.Mvc.Controller;
using Nop.Plugin.Baramjk.Framework.Mvc.Filters;
using Nop.Plugin.Baramjk.PhotoPlatform.Areas.Admin.Factories;
using Nop.Plugin.Baramjk.PhotoPlatform.Areas.Admin.Models.Subjects;
using Nop.Plugin.Baramjk.PhotoPlatform.Domains;
using Nop.Plugin.Baramjk.PhotoPlatform.Plugins;
using Nop.Plugin.Baramjk.PhotoPlatform.Services.ContactUs;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Web.Framework;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Baramjk.PhotoPlatform.Areas.Admin.Controllers
{
    [Permission(PermissionProvider.ManagementName)]
    [Area(AreaNames.Admin)]
    [Route("Admin/PhotoPlatform/[controller]/[action]")]
    public class ContactUsSubjectController : BaseBaramjkPluginController
    {
        private readonly SubjectAdminFactory _subjectAdminFactory;
        private readonly PhotoPlatformSubjectService _subjectService;
        private readonly INotificationService _notificationService;
        private readonly ILocalizedEntityService _localizedEntityService;

        public ContactUsSubjectController(
            SubjectAdminFactory subjectAdminFactory,
            PhotoPlatformSubjectService subjectService,
            INotificationService notificationService,
            ILocalizedEntityService localizedEntityService)
        {
            _subjectAdminFactory = subjectAdminFactory;
            _subjectService = subjectService;
            _notificationService = notificationService;
            _localizedEntityService = localizedEntityService;
        }

        protected override string GetViewPath(string viewName)
        {
            return $"~/Plugins/{SystemName}/Areas/Admin/Views/ContactUs/{ControllerName}/{viewName}";
        }

        private async Task UpdateLocalizedAsync(SubjectViewModel viewModel, SubjectEntity entity)
        {
            foreach (var localized in viewModel.Locales)
            {
                await _localizedEntityService.SaveLocalizedValueAsync(entity,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);
            }
        }


        [HttpGet]
        public IActionResult ListAsync()
        {
            var searchModel = _subjectAdminFactory.PrepareSearchModel();
            return View("List.cshtml", searchModel);
        }

        [HttpPost]
        public async Task<IActionResult> ListAsync(SubjectSearchModel searchModel)
        {
            var model = await _subjectAdminFactory.PrepareListModelAsync(searchModel);
            return Json(model);
        }

        [HttpGet]
        public async Task<IActionResult> CreateAsync()
        {
            var viewModel = await _subjectAdminFactory.PrepareViewModelAsync();
            return View("Create.cshtml", viewModel);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public async Task<IActionResult> CreateAsync(SubjectViewModel viewModel, bool continueEditing)
        {
            if (string.IsNullOrEmpty(viewModel.Name))
            {
                _notificationService.ErrorNotification("Invalid name.");
                return View("Create.cshtml", viewModel);
            }

            var entity = new SubjectEntity
            {
                Name = viewModel.Name,
            };

            await _subjectService.InsertAsync(entity);
            await UpdateLocalizedAsync(viewModel, entity);

            return continueEditing
                ? RedirectToAction("Edit", new { id = entity.Id })
                : RedirectToAction("List");
        }

        [HttpGet("{id:int}")]
        public async Task<IActionResult> EditAsync(int id)
        {
            var entity = await _subjectService.GetByIdAsync(id);
            if (entity == null)
                return RedirectToAction("List");

            var model = await _subjectAdminFactory.PrepareViewModelAsync(entity);
            return View("Edit.cshtml", model);
        }

        [HttpPost("{id:int}"), ParameterBasedOnFormName("save-continue", "continueEditing")]
        public async Task<IActionResult> EditAsync(int id, SubjectViewModel viewModel, bool continueEditing)
        {
            if (id != viewModel.Id)
                return RedirectToAction("List");

            if (string.IsNullOrEmpty(viewModel.Name))
            {
                _notificationService.ErrorNotification("Invalid name.");
                return View("Edit.cshtml", viewModel);
            }

            var entity = await _subjectService.GetByIdAsync(viewModel.Id);
            if (entity == null)
            {
                _notificationService.ErrorNotification("Subject not found.");
                return RedirectToAction("List");
            }

            entity.Name = viewModel.Name;


            await _subjectService.UpdateAsync(entity);

            await UpdateLocalizedAsync(viewModel, entity);

            _notificationService.SuccessNotification("Subject has been saved.");

            return continueEditing
                ? RedirectToAction("Edit", new { id = entity.Id })
                : RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteByIdAsync(int id)
        {
            await _subjectService.DeleteAsync(id);
            return new NullJsonResult();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _subjectService.DeleteAsync(id);
            return RedirectToAction("List");
        }
    }
}

Plugins/Nop.Plugin.Baramjk.PhotoPlatform/Areas/Admin/Views/ContactUs/ContactUsSubject/Create.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Nop.Plugin.Baramjk.PhotoPlatform.Areas.Admin.Models.Subjects.SubjectViewModel


@{
    ViewBag.PageTitle = T("Nop.Plugin.Baramjk.PhotoPlatform.ContactUs.Admin.Subjects.AddSubject").Text;
    Html.SetActiveMenuItemSystemName($"{SystemName}.ContactUsSubjects.List");
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-controller="ContactUsSubject" asp-action="Create" method="post" id="items-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Nop.Plugin.Baramjk.PhotoPlatform.ContactUs.Admin.Subjects.AddSubject")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-controller="ContactUsSubject" asp-action="List">@T("Nop.Plugin.Baramjk.PhotoPlatform.ContactUs.Admin.Subjects.BackToSubjectsList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
        </div>
    </div>
    @await Html.PartialAsync($"~/Plugins/{SystemName}/Areas/Admin/Views/ContactUs/{ControllerName}/_CreateOrUpdate.cshtml", Model)
</form>

Plugins/Nop.Plugin.Baramjk.PhotoPlatform/Areas/Admin/Views/ContactUs/ContactUsSubject/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Nop.Web.Framework.TagHelpers.Admin
@model Nop.Plugin.Baramjk.PhotoPlatform.Areas.Admin.Models.Subjects.SubjectViewModel


@{
    ViewBag.PageTitle = T("Nop.Plugin.Baramjk.PhotoPlatform.ContactUs.Admin.Subjects.EditSubject").Text;
    Html.SetActiveMenuItemSystemName($"{SystemName}.ContactUsSubjects.List");
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-controller="ContactUsSubject" asp-action="Edit" method="post" id="items-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Nop.Plugin.Baramjk.PhotoPlatform.ContactUs.Admin.Subjects.EditSubject")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-controller="ContactUsSubject" asp-action="List">@T("Nop.Plugin.Baramjk.PhotoPlatform.ContactUs.Admin.Subjects.BackToSubjectsList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="item-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
        </div>
    </div>
    @await Html.PartialAsync($"~/Plugins/{SystemName}/Areas/Admin/Views/ContactUs/{ControllerName}/_CreateOrUpdate.cshtml", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="item-delete" />

Plugins/Nop.Plugin.Baramjk.PhotoPlatform/Areas/Admin/Views/ContactUs/ContactUsSubject/List.cshtml
@using Nop.Plugin.Baramjk.PhotoPlatform.Areas.Admin.Models.Subjects
@using Nop.Web.Framework.Models.DataTables
@model Nop.Plugin.Baramjk.PhotoPlatform.Areas.Admin.Models.Subjects.SubjectSearchModel

@{
    ViewBag.PageTitle = T("Nop.Plugin.Baramjk.PhotoPlatform.ContactUs.Admin.Subjects.Title").Text;
    Html.SetActiveMenuItemSystemName($"{SystemName}.ContactUsSubjects.List");
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-header clearfix">
    <h1 class="float-left">
        @T("Nop.Plugin.Baramjk.PhotoPlatform.ContactUs.Admin.Subjects.Title")
    </h1>
    <div class="float-right">
        <a asp-action="Create" asp-controller="ContactUsSubject" class="btn btn-primary">
            <i class="fas fa-plus-square"></i>
            @T("Admin.Common.AddNew")
        </a>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <div class="form-horizontal">
            <div class="card card-default">
                <div class="card-body">
                    @await Html.PartialAsync("Table", new DataTablesModel
                    {
                        Name = "subjects-grid",
                        UrlRead = new DataUrl("List", "ContactUsSubject", null),
                        UrlUpdate = new DataUrl("Edit", "ContactUsSubject", null),
                        UrlDelete = new DataUrl("DeleteById", "ContactUsSubject", null),
                        Length = Model.PageSize,
                        LengthMenu = Model.AvailablePageSizes,
                        ColumnCollection = new List<ColumnProperty>
                        {
                            new(nameof(SubjectViewModel.Name))
                            {
                                Title = T("Nop.Plugin.Baramjk.PhotoPlatform.ContactUs.Admin.Subjects.Name").Text,
                            },
                            
                            new(nameof(SubjectViewModel.Id))
                            {
                                Title = T("Admin.Common.Edit").Text,
                                Width = "50",
                                ClassName = NopColumnClassDefaults.Button,
                                Render = new RenderButtonEdit(new DataUrl("Edit"))
                            },
                            new(nameof(SubjectViewModel.Id))
                            {
                                Title = T("Admin.Common.Delete").Text,
                                Width = "50",
                                ClassName = NopColumnClassDefaults.Button,
                                Render = new RenderButtonRemove(T("Admin.Common.Delete").Text)
                            }
                        }
                    })
                </div>
            </div>
        </div>
    </div>
</section>

Plugins/Nop.Plugin.Baramjk.PhotoPlatform/Areas/Admin/Views/ContactUs/ContactUsSubject/_CreateOrUpdate.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Nop.Plugin.Baramjk.PhotoPlatform.Areas.Admin.Models.Subjects
@using Nop.Web.Framework.TagHelpers.Admin
@model Nop.Plugin.Baramjk.PhotoPlatform.Areas.Admin.Models.Subjects.SubjectViewModel

<input asp-for="Id" type="hidden"/>

<section class="content">
    <div class="container-fluid">
        <div class="form-horizontal">
            <div class="card card-default">
                <div class="card-body">
                    @(await Html.LocalizedEditorAsync<SubjectViewModel, SubjectLocalizedModel>("subject-localized",
                        @<div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="@Model.Locales[item].Name"/>
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="@Model.Locales[item].Name"/>
                                    <span asp-validation-for="@Model.Locales[item].Name"></span>
                                </div>
                            </div>
                            <input type="hidden" asp-for="@Model.Locales[item].LanguageId"/>
                        </div>,
                        @<div>
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="Name"/>
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="Name" asp-required="true"/>
                                    <span asp-validation-for="Name"></span>
                                </div>
                            </div>
                        </div>))

                   
                </div>
            </div>
        </div>
    </div>
</section>